### ISSUE TITLE
adb not found

### ISSUE THREAD

**Issue by BJS611** [Iqbalmh18/adbsploit#1]
[*] connecting with serialno in: shodan_105837.txtsh: adb: not found
![Screenshot_2020-10-17-11-00-43-31_84d3000e3f4017145260f7618db1d683](https://user-images.githubusercontent.com/65802479/96327893-061ae080-1068-11eb-8b12-5ef9a1f8d99c.png)

Tolong solusinya mas, terimakasih.

**Comment by BJS611** [comment]
#Solved

Saya menggunakan ubuntu di termux dan sukses![Screenshot_2020-10-17-12-07-11-07_84d3000e3f4017145260f7618db1d683.png](https://user-images.githubusercontent.com/65802479/96328875-bd682500-1071-11eb-86de-8438f2d9472f.png)

**Comment by Iqbalmh18** [comment]
Thanks for make an issues, but in this case u have to install Adbtool in your termux, i have writted cmd for installing this in option 2 ( install for termux).

![Screenshot_2020-10-19-12-04-19-23_a2cf8efcdd42a8e6f7906303f104fb67](https://user-images.githubusercontent.com/41185294/96403703-3e0a5b00-1203-11eb-9c8f-98cfc865f122.jpg)

Termux Adb by @MasterDevX
https://github.com/MasterDevX/Termux-ADB
